/* ═══════════════════════════════════════════════════════
   SkillBridge — Application Data
   Replace placeholder values with real content before launch.
   ═══════════════════════════════════════════════════════ */

const DOMAINS = [
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    icon: '🔐',
    accentClass: 'coral',
    department: 'Computer Engineering',
    tagline: 'Defend. Detect. Hack ethically.',
    description: 'Join the Cybersecurity community to learn network defense, ethical hacking, and compete in Capture The Flag challenges.',
    roadmap: [
      { month: 1, title: 'Foundations', topics: ['Networking basics', 'Linux CLI', 'Security mindset'] },
      { month: 2, title: 'Offensive Skills', topics: ['Scanning & enumeration', 'Nmap', 'Web vulnerabilities'] },
      { month: 3, title: 'CTF Labs', topics: ['HackTheBox', 'TryHackMe', 'Team competitions'] },
      { month: 4, title: 'Real Projects', topics: ['Security audit', 'Client report', 'Portfolio'] },
    ],
    features: ['Weekly CTF challenges', 'Mentor-led sessions', 'Internship referrals', 'Community chat'],
  },
  {
    id: 'aiml',
    name: 'AI & Machine Learning',
    icon: '🤖',
    accentClass: 'purple',
    department: 'AI & Data Science Engineering',
    tagline: 'Build systems that learn.',
    description: 'From Python fundamentals to deploying production ML models. Work on real datasets and Kaggle competitions.',
    roadmap: [
      { month: 1, title: 'Python & Math', topics: ['NumPy', 'Pandas', 'Linear Algebra refresher'] },
      { month: 2, title: 'ML Basics', topics: ['Scikit-learn', 'Regression & Classification', 'Model eval'] },
      { month: 3, title: 'Deep Learning', topics: ['PyTorch basics', 'CNNs', 'NLP intro'] },
      { month: 4, title: 'Deploy & Ship', topics: ['FastAPI', 'HuggingFace', 'Capstone project'] },
    ],
    features: ['Kaggle sprint events', 'Research paper reading club', 'GPU access (shared)', 'Project reviews'],
  },
  {
    id: 'webdev',
    name: 'Web Development',
    icon: '💻',
    accentClass: 'blue',
    department: 'Computer Engineering',
    tagline: 'Ship products people use.',
    description: 'Build modern full-stack web applications. Work on live client projects and build a portfolio that gets you hired.',
    roadmap: [
      { month: 1, title: 'HTML & CSS', topics: ['Semantic HTML', 'Flexbox & Grid', 'Responsive design'] },
      { month: 2, title: 'JavaScript & React', topics: ['ES6+', 'React hooks', 'State management'] },
      { month: 3, title: 'Backend', topics: ['Node.js / Express', 'REST APIs', 'Databases'] },
      { month: 4, title: 'Client Work', topics: ['Real client brief', 'Deployment', 'Portfolio launch'] },
    ],
    features: ['Frontend hackathons', 'Code review sessions', 'Client project matching', 'Job prep workshops'],
  },
  {
    id: 'cloud',
    name: 'Cloud & DevOps',
    icon: '☁️',
    accentClass: 'teal',
    department: 'Computer Engineering',
    tagline: 'Scale infrastructure. Automate everything.',
    description: 'Learn cloud platforms, CI/CD pipelines, and infrastructure-as-code. Deploy real projects on AWS and GCP.',
    roadmap: [
      { month: 1, title: 'Cloud Basics', topics: ['AWS/GCP overview', 'S3, EC2', 'Networking 101'] },
      { month: 2, title: 'Services & IaC', topics: ['Terraform basics', 'Lambda', 'RDS'] },
      { month: 3, title: 'DevOps', topics: ['Docker', 'GitHub Actions', 'CI/CD pipelines'] },
      { month: 4, title: 'Deploy Projects', topics: ['Production deployment', 'Monitoring', 'Cost optimisation'] },
    ],
    features: ['Cloud credit grants', 'Certification prep', 'Architecture review sessions', 'Industry guest talks'],
  },
  {
    id: 'datascience',
    name: 'Data Science',
    icon: '📊',
    accentClass: 'teal',
    department: 'AI & Data Science Engineering',
    tagline: 'Turn data into decisions.',
    description: 'Analyze real-world datasets, build visualizations, and present insights that drive business decisions.',
    roadmap: [
      { month: 1, title: 'Stats & Excel', topics: ['Descriptive stats', 'Hypothesis testing', 'Pivot tables'] },
      { month: 2, title: 'Python Analysis', topics: ['Pandas', 'Matplotlib', 'Seaborn'] },
      { month: 3, title: 'Visualization', topics: ['Plotly dashboards', 'Tableau', 'Storytelling with data'] },
      { month: 4, title: 'Case Study', topics: ['End-to-end project', 'Presentation to panel', 'Report writing'] },
    ],
    features: ['Dataset library access', 'Visualisation workshops', 'Industry case studies', 'Hackathons'],
  },
  {
    id: 'uiux',
    name: 'UI / UX Design',
    icon: '🎨',
    accentClass: 'pink',
    department: 'Management Studies',
    tagline: 'Design experiences, not just screens.',
    description: 'Learn user research, wireframing, and high-fidelity design. Build a portfolio of real client work in Figma.',
    roadmap: [
      { month: 1, title: 'Design Theory', topics: ['Typography', 'Color theory', 'Design systems'] },
      { month: 2, title: 'Figma', topics: ['Components', 'Auto-layout', 'Prototyping'] },
      { month: 3, title: 'User Research', topics: ['Interviews', 'Usability testing', 'Affinity maps'] },
      { month: 4, title: 'Client Brief', topics: ['Real project', 'Pitch presentation', 'Portfolio update'] },
    ],
    features: ['Figma Education licence', 'Design critique sessions', 'Client project briefs', 'Portfolio reviews'],
  },
  {
    id: 'robotics',
    name: 'Robotics',
    icon: '🦾',
    accentClass: 'amber',
    department: 'Automation & Robotics Engineering',
    tagline: 'Build machines that move.',
    description: 'Program real robots, compete in robo-race events, and work with Arduino and sensor systems.',
    roadmap: [
      { month: 1, title: 'Electronics', topics: ['Circuit basics', 'Arduino IDE', 'Sensors intro'] },
      { month: 2, title: 'Programming', topics: ['C for Arduino', 'Motor control', 'Servo systems'] },
      { month: 3, title: 'Sensors & Vision', topics: ['Ultrasonic', 'Camera modules', 'Line follower'] },
      { month: 4, title: 'Build & Compete', topics: ['Full robot build', 'Robo-race entry', 'Project demo'] },
    ],
    features: ['Hardware lab access', 'Component library', 'Robo-race competitions', 'Industry mentor visits'],
  },
  {
    id: 'mechanicalcad',
    name: 'CAD & Mech Design',
    icon: '⚙️',
    accentClass: 'amber',
    department: 'Mechanical Engineering',
    tagline: 'Design. Simulate. Manufacture.',
    description: 'Master SolidWorks and AutoCAD, run FEA simulations, and build real prototypes with 3D printing.',
    roadmap: [
      { month: 1, title: 'Engineering Drawing', topics: ['GD&T', '2D drafting', 'Projection views'] },
      { month: 2, title: 'SolidWorks', topics: ['Part modelling', 'Assembly', 'Sheet metal'] },
      { month: 3, title: 'FEA Basics', topics: ['Simulation study', 'Stress analysis', 'Mesh settings'] },
      { month: 4, title: 'Prototype', topics: ['3D print prep', 'Physical build', 'Design review'] },
    ],
    features: ['SolidWorks EDU licence', '3D printer access', 'CAD challenge events', 'Industry project briefs'],
  },
  {
    id: 'structural',
    name: 'Structural Tech',
    icon: '🏗️',
    accentClass: 'teal',
    department: 'Civil Engineering',
    tagline: 'Engineer structures that stand.',
    description: 'Apply civil engineering principles to real structural challenges, from bridge design to site surveys.',
    roadmap: [
      { month: 1, title: 'Materials', topics: ['Concrete properties', 'Steel grades', 'Load types'] },
      { month: 2, title: 'AutoCAD', topics: ['2D plans', 'Sections & elevations', 'Standard templates'] },
      { month: 3, title: 'Structural Analysis', topics: ['Beam theory', 'STAAD.Pro intro', 'Load calculations'] },
      { month: 4, title: 'Project', topics: ['Design submission', 'Peer review', 'Client presentation'] },
    ],
    features: ['AutoCAD EDU licence', 'Field visit sessions', 'Bridge design competition', 'Industry site tours'],
  },
];

const DEPARTMENTS = ['All', 'Computer Engineering', 'AI & Data Science Engineering',
  'Automation & Robotics Engineering', 'Mechanical Engineering', 'Civil Engineering', 'Management Studies'];

const JOBS = [
  {
    id: 'j001',
    domain: 'cybersecurity',
    company: 'Local IT firm — Nashik',
    title: 'Cybersecurity Intern',
    type: 'Internship',
    stipend: 'Paid',
    location: 'Nashik',
    description: 'Assist in vulnerability assessments and network monitoring for regional SME clients. Requires basic knowledge of Nmap and Linux.',
    skills: ['Linux', 'Nmap', 'Network basics'],
    deadline: '2026-05-15',
  },
  {
    id: 'j002',
    domain: 'aiml',
    company: 'AgriTech Startup — Remote',
    title: 'ML Engineer Intern',
    type: 'Internship',
    stipend: 'Paid',
    location: 'Remote',
    description: 'Work on NLP pipelines and assist with model training for a precision agriculture product. Python and basic ML knowledge required.',
    skills: ['Python', 'Scikit-learn', 'Pandas'],
    deadline: '2026-05-20',
  },
  {
    id: 'j003',
    domain: 'webdev',
    company: 'Local Startup Hub — Nashik',
    title: 'Frontend Developer (Part-time)',
    type: 'Part-time',
    stipend: 'Paid',
    location: 'Nashik',
    description: 'Build and maintain React dashboards for local business clients. Git workflow and HTML/CSS/JS fundamentals required.',
    skills: ['React', 'CSS', 'Git'],
    deadline: '2026-05-10',
  },
  {
    id: 'j004',
    domain: 'datascience',
    company: 'Regional NGO — Nashik',
    title: 'Data Analyst Intern',
    type: 'Internship',
    stipend: 'Certificate + allowance',
    location: 'Nashik',
    description: 'Analyze beneficiary data and produce monthly visual reports for an education-focused NGO. Excel and basic Python required.',
    skills: ['Excel', 'Python', 'Data visualisation'],
    deadline: '2026-05-30',
  },
  {
    id: 'j005',
    domain: 'uiux',
    company: 'Design Studio — Nashik',
    title: 'UI/UX Design Intern',
    type: 'Internship',
    stipend: 'Paid',
    location: 'Nashik',
    description: 'Design user flows, wireframes, and Figma prototypes for 2–3 active client projects across retail and education.',
    skills: ['Figma', 'User research', 'Prototyping'],
    deadline: '2026-05-18',
  },
  {
    id: 'j006',
    domain: 'cloud',
    company: 'Cloud Services Provider — Remote',
    title: 'Cloud Operations Intern',
    type: 'Internship',
    stipend: 'Paid',
    location: 'Remote',
    description: 'Assist in managing AWS infrastructure, writing Terraform scripts, and setting up CI/CD pipelines for client environments.',
    skills: ['AWS basics', 'Linux', 'Docker'],
    deadline: '2026-05-25',
  },
  {
    id: 'j007',
    domain: 'robotics',
    company: 'Automation Lab — Nashik',
    title: 'Robotics Project Intern',
    type: 'Internship',
    stipend: 'Stipend + components',
    location: 'Nashik',
    description: 'Assemble and program Arduino-based automation systems for a warehouse robotics proof-of-concept project.',
    skills: ['Arduino', 'C/C++', 'Sensors'],
    deadline: '2026-06-01',
  },
  {
    id: 'j008',
    domain: 'webdev',
    company: 'Nashik NGO — Volunteer+',
    title: 'Web Developer (Social Impact)',
    type: 'Social Project',
    stipend: 'Certificate + letter',
    location: 'Nashik',
    description: 'Build an awareness and donation landing page for a local NGO working in rural education. Full ownership of design and code.',
    skills: ['HTML', 'CSS', 'JavaScript'],
    deadline: '2026-05-12',
  },
  {
    id: 'j009',
    domain: 'cybersecurity',
    company: 'Retail Business — Nashik',
    title: 'Security Audit (Freelance)',
    type: 'Freelance Project',
    stipend: 'Fixed fee',
    location: 'Nashik',
    description: 'Conduct a basic website vulnerability scan and deliver a written security report with remediation recommendations.',
    skills: ['Vulnerability scanning', 'Report writing', 'Linux'],
    deadline: '2026-05-08',
  },
  {
    id: 'j010',
    domain: 'mechanicalcad',
    company: '3D Print Workshop — Nashik',
    title: 'CAD Design Intern',
    type: 'Internship',
    stipend: 'Paid',
    location: 'Nashik',
    description: 'Model mechanical components in SolidWorks and prepare files for FDM 3D printing. Basic SolidWorks skills required.',
    skills: ['SolidWorks', '3D printing', 'GD&T'],
    deadline: '2026-06-05',
  },
];

const MENTORS = [
  {
    id: 'm001',
    name: 'Rahul Deshmukh',
    initials: 'RD',
    role: 'Senior Security Engineer',
    company: 'Infosys Pune',
    domain: 'cybersecurity',
    accentClass: 'coral',
    expertise: ['Penetration testing', 'VAPT', 'Network security'],
    sessionFormat: 'Bi-weekly 1:1 + group workshop',
    available: true,
  },
  {
    id: 'm002',
    name: 'Priya Kulkarni',
    initials: 'PK',
    role: 'ML Research Lead',
    company: 'TCS Research',
    domain: 'aiml',
    accentClass: 'purple',
    expertise: ['NLP', 'Computer vision', 'MLOps'],
    sessionFormat: 'Weekly office hours + async review',
    available: true,
  },
  {
    id: 'm003',
    name: 'Amit Shah',
    initials: 'AS',
    role: 'Full Stack Developer',
    company: 'Freelance / ex-Flipkart',
    domain: 'webdev',
    accentClass: 'blue',
    expertise: ['React', 'Node.js', 'System design'],
    sessionFormat: 'Fortnightly code review sessions',
    available: true,
  },
  {
    id: 'm004',
    name: 'Sneha Joshi',
    initials: 'SJ',
    role: 'Data Scientist',
    company: 'Regional AgriTech firm',
    domain: 'datascience',
    accentClass: 'teal',
    expertise: ['EDA', 'Time series', 'Business storytelling'],
    sessionFormat: 'Monthly workshop + async Q&A',
    available: true,
  },
  {
    id: 'm005',
    name: 'Kiran Patil',
    initials: 'KP',
    role: 'Cloud Architect',
    company: 'AWS Consulting Partner',
    domain: 'cloud',
    accentClass: 'teal',
    expertise: ['AWS Solutions Architect', 'Terraform', 'Kubernetes'],
    sessionFormat: 'Bi-weekly group call + Discord',
    available: false,
  },
  {
    id: 'm006',
    name: 'Deepa Nair',
    initials: 'DN',
    role: 'UX Lead',
    company: 'Product design studio, Nashik',
    domain: 'uiux',
    accentClass: 'pink',
    expertise: ['User research', 'Design systems', 'Figma advanced'],
    sessionFormat: 'Weekly portfolio critique + brief',
    available: true,
  },
  {
    id: 'm007',
    name: 'Rohan More',
    initials: 'RM',
    role: 'Robotics Engineer',
    company: 'Automation startup, Pune',
    domain: 'robotics',
    accentClass: 'amber',
    expertise: ['Arduino', 'ROS basics', 'Embedded C'],
    sessionFormat: 'Monthly lab session + chat support',
    available: true,
  },
];

/* ─── Accent colour maps ──────────────────────────────── */
const ACCENT_BG = {
  coral:  '#FAE4DC', purple: '#ECEAFE', blue: '#E4EFFC',
  teal:   '#D9F0E8', pink:   '#FAE4F0', amber: '#FDE8C8',
};
const ACCENT_TC = {
  coral:  '#A83B20', purple: '#4A3BAF', blue: '#185FA5',
  teal:   '#0F6E56', pink:   '#993556', amber: '#B06B10',
};
